- .gitignore
- .npmignore
- .zuul.yml
- README.md
- examples/browser/.gitignore
- examples/browser/README.md
- examples/browser/index.html
- examples/browser/index.js
- examples/browser/package.json
- examples/browser/test.js
- package.json
- test/Holidays.mocha.js
- test/lib/helper.js
- test/mocha.opts
This PR adds browser tests with zuul together with a simple example for any modern browser.
> Browser example and tests

- data/countries/ES.yaml
- data/holidays.json
- test/fixtures/ES-AN-2015.json
- test/fixtures/ES-AN-2016.json
- test/fixtures/ES-AN-2017.json
- test/fixtures/ES-AN-2018.json
- test/fixtures/ES-AN-2019.json
- test/fixtures/ES-AN-2020.json
Added holidays of Andalucia and change name of Andalusia to Andalucía.
> added holidays of Andalucia

- docs/specification.md
> doc: document renaming of holidays

- package.json
Welcome to Ryan as new (co)-maintainer.
Thanks for having you on-board.
> new maintainer

- examples/browser/.gitignore
- examples/browser/.npmrc
- examples/browser/README.md
- examples/browser/index.html
- examples/browser/index.js
- examples/browser/package.json
- examples/browser/test.js
update browser example using module version from CDN.
> feat: update using cdn; download calendar

- data/countries/CH.yaml
fixes issue https://github.com/commenthol/date-holidays-parser/issues/8
> fix(CH): adding dayoff attribute

- data/countries/ES.yaml
- test/fixtures/ES-CT-2015.json
- test/fixtures/ES-CT-2016.json
- test/fixtures/ES-CT-2017.json
- test/fixtures/ES-CT-2018.json
- test/fixtures/ES-CT-2019.json
- test/fixtures/ES-CT-2020.json
Source: https://ajuntament.barcelona.cat/calendarifestius/ca/
> New dates for Catalonia State of Spain. 

- types/index.d.ts
https://github.com/commenthol/date-holidays/issues/117
> Fix isHoliday return type

- types/index.d.ts
- types/typings.test.ts
I just realised I forgot to update the typing in the class as well, it was only done in the interface.
Sorry for that, fixed it now 😅
> Fix(Types): Reflected change of isHoliday to class

- README.md
- data/countries/GB.yaml
> fix(#127): Fix Typo in Scotland

- types/index.d.ts
> Fix typings for setLanguages function

- LICENSE
- data/countries/DK.yaml
- data/names.yaml
- test/fixtures/DK-2015.json
- test/fixtures/DK-2016.json
- test/fixtures/DK-2017.json
- test/fixtures/DK-2018.json
- test/fixtures/DK-2019.json
- test/fixtures/DK-2020.json
- 1.maj
- note on Constitution Day
- Christmas Eve
Fixes issue #129
> fix(#129,DK): add observance holidays

- data/countries/CZ.yaml
- data/names.yaml
Updated czech easter holiday names and fixed some naming.
> Czech holidays patch

- data/countries/SE.yaml
- data/names.yaml
- test/fixtures/SE-2015.json
- test/fixtures/SE-2016.json
- test/fixtures/SE-2017.json
- test/fixtures/SE-2018.json
- test/fixtures/SE-2019.json
- test/fixtures/SE-2020.json
- test/fixtures/SE-2021.json
- test/fixtures/SE-2022.json
- test/fixtures/SE-2023.json
- test/fixtures/SE-2024.json
- test/fixtures/SE-2025.json
- fixes the correct type of bank holidays
- fixes naming of "Tjugondag knut"
- added missing holidays
> fix(SE.*): fix holidays for SE

- data/countries/TG.yaml
> fix(TG): add country name

- data/countries/SE.yaml
- data/names.yaml
- test/fixtures/AX-2015.json
- test/fixtures/AX-2016.json
- test/fixtures/AX-2017.json
- test/fixtures/AX-2018.json
- test/fixtures/AX-2019.json
- test/fixtures/AX-2020.json
- test/fixtures/AX-2021.json
- test/fixtures/AX-2022.json
- test/fixtures/AX-2023.json
- test/fixtures/AX-2024.json
- test/fixtures/AX-2025.json
- test/fixtures/SE-2015.json
- test/fixtures/SE-2016.json
- test/fixtures/SE-2017.json
- test/fixtures/SE-2018.json
- test/fixtures/SE-2019.json
- test/fixtures/SE-2020.json
- test/fixtures/SE-2021.json
- test/fixtures/SE-2022.json
- test/fixtures/SE-2023.json
- test/fixtures/SE-2024.json
- test/fixtures/SE-2025.json
> fix(SE): #165 missing evenings

- package.json
> fix: export data

- package.json
- types/index.d.ts
- types/typings.test.ts
Fix typescript typings and bump dependencies to use date-holidays-parser v3.1.0
> Fix typings

- data/countries/MG.yaml
- test/fixtures/MG-2015.json
- test/fixtures/MG-2016.json
- test/fixtures/MG-2017.json
- test/fixtures/MG-2018.json
- test/fixtures/MG-2019.json
- test/fixtures/MG-2020.json
- test/fixtures/MG-2021.json
- test/fixtures/MG-2022.json
- test/fixtures/MG-2023.json
- test/fixtures/MG-2024.json
- test/fixtures/MG-2025.json
I have add some holidays for Madagascar.
> feat(MG): Add holidays for country Madagascar

- data/countries/GP.yaml
- test/fixtures/FR-GP-2015.json
- test/fixtures/FR-GP-2016.json
- test/fixtures/FR-GP-2017.json
- test/fixtures/FR-GP-2018.json
- test/fixtures/FR-GP-2019.json
- test/fixtures/FR-GP-2020.json
- test/fixtures/FR-GP-2021.json
- test/fixtures/FR-GP-2022.json
- test/fixtures/FR-GP-2023.json
- test/fixtures/FR-GP-2024.json
- test/fixtures/FR-GP-2025.json
- test/fixtures/GP-2015.json
- test/fixtures/GP-2016.json
- test/fixtures/GP-2017.json
- test/fixtures/GP-2018.json
- test/fixtures/GP-2019.json
- test/fixtures/GP-2020.json
- test/fixtures/GP-2021.json
- test/fixtures/GP-2022.json
- test/fixtures/GP-2023.json
- test/fixtures/GP-2024.json
- test/fixtures/GP-2025.json
Pentecost disabled and add one holiday for 07-21
> fix(GP): Update holidays Guadeloupe

- data/countries/MQ.yaml
- test/fixtures/FR-MQ-2015.json
- test/fixtures/FR-MQ-2016.json
- test/fixtures/FR-MQ-2017.json
- test/fixtures/FR-MQ-2018.json
- test/fixtures/FR-MQ-2019.json
- test/fixtures/FR-MQ-2020.json
- test/fixtures/FR-MQ-2021.json
- test/fixtures/FR-MQ-2022.json
- test/fixtures/FR-MQ-2023.json
- test/fixtures/FR-MQ-2024.json
- test/fixtures/FR-MQ-2025.json
- test/fixtures/MQ-2015.json
- test/fixtures/MQ-2016.json
- test/fixtures/MQ-2017.json
- test/fixtures/MQ-2018.json
- test/fixtures/MQ-2019.json
- test/fixtures/MQ-2020.json
- test/fixtures/MQ-2021.json
- test/fixtures/MQ-2022.json
- test/fixtures/MQ-2023.json
- test/fixtures/MQ-2024.json
- test/fixtures/MQ-2025.json
Pentecost disabled and add one holiday for 07-21
> fix(MQ): Martinique 

- .github/workflows/ci.yml
Enable ci pipeline for pull requests
> chore(ci): run github actions for pull requests

- data/countries/RU.yaml
Hi!
Thank you so much for this amazing international project with holidays
But with Decree№1564 of 16.09.21 we haven't holiday National Flag Day 22/08 in Russia
Please merge it in project
Thank you :)
> Changes in public Ru holidays

- data/countries/SG.yaml
- test/fixtures/SG-2022.json
> feat: update SG Holidays

- data/countries/AR.yaml
- data/names.yaml
- test/fixtures/AR-2015.json
- test/fixtures/AR-2016.json
- test/fixtures/AR-2017.json
- test/fixtures/AR-2018.json
- test/fixtures/AR-2019.json
- test/fixtures/AR-2020.json
- test/fixtures/AR-2021.json
- test/fixtures/AR-2022.json
- test/fixtures/AR-2023.json
- test/fixtures/AR-2024.json
- test/fixtures/AR-2025.json
> fix(AR,#343): Feriado Puente Turístico

- data/countries/DE.yaml
- test/fixtures/DE-MV-2023.json
- test/fixtures/DE-MV-2024.json
- test/fixtures/DE-MV-2025.json
> fix(DE-MV): International Women's Day

- data/countries/FI.yaml
- test/fixtures/FI-2015.json
- test/fixtures/FI-2016.json
- test/fixtures/FI-2017.json
- test/fixtures/FI-2018.json
- test/fixtures/FI-2019.json
- test/fixtures/FI-2020.json
- test/fixtures/FI-2021.json
- test/fixtures/FI-2022.json
- test/fixtures/FI-2023.json
- test/fixtures/FI-2024.json
- test/fixtures/FI-2025.json
closes https://github.com/commenthol/date-holidays/issues/392
> issue-392, fix Finland's incorrect New Year's Eve rule

- data/countries/IE.yaml
- test/fixtures/IE-2023.json
- test/fixtures/IE-2024.json
- test/fixtures/IE-2025.json
> fix(IE): new public holiday St. Brigid's Day

- data/names.yaml
> added swedish translation for Father's day #401

- data/countries/NO.yaml
- test/fixtures/NO-2015.json
- test/fixtures/NO-2016.json
- test/fixtures/NO-2017.json
- test/fixtures/NO-2018.json
- test/fixtures/NO-2019.json
- test/fixtures/NO-2020.json
- test/fixtures/NO-2021.json
- test/fixtures/NO-2022.json
- test/fixtures/NO-2023.json
- test/fixtures/NO-2024.json
- test/fixtures/NO-2025.json
- test/fixtures/NO-2026.json
- test/fixtures/NO-2027.json
- test/fixtures/SJ-2015.json
- test/fixtures/SJ-2016.json
- test/fixtures/SJ-2017.json
- test/fixtures/SJ-2018.json
- test/fixtures/SJ-2019.json
- test/fixtures/SJ-2020.json
- test/fixtures/SJ-2021.json
- test/fixtures/SJ-2022.json
- test/fixtures/SJ-2023.json
- test/fixtures/SJ-2024.json
- test/fixtures/SJ-2025.json
- test/fixtures/SJ-2026.json
- test/fixtures/SJ-2027.json
Correct the kings birthday to observance, as it is not a public holiday
> Correction to holiday in Norway

- data/countries/US.yaml
- test/fixtures/US-VA-2015.json
- test/fixtures/US-VA-2016.json
- test/fixtures/US-VA-2017.json
- test/fixtures/US-VA-2018.json
- test/fixtures/US-VA-2019.json
- test/fixtures/US-VA-2020.json
- test/fixtures/US-VA-2021.json
- test/fixtures/US-VA-2022.json
- test/fixtures/US-VA-2023.json
- test/fixtures/US-VA-2024.json
- test/fixtures/US-VA-2025.json
- test/fixtures/US-VA-2026.json
- test/fixtures/US-VA-2027.json
https://en.wikipedia.org/wiki/Lee–Jackson_Day
Replace PR #396
> feat: remove Lee-Jackson Day starting 2020, add Election Day

- data/countries/CA.yaml
- test/fixtures/CA-NT-2015.json
- test/fixtures/CA-NT-2016.json
- test/fixtures/CA-NT-2017.json
- test/fixtures/CA-NT-2018.json
- test/fixtures/CA-NT-2019.json
- test/fixtures/CA-NT-2020.json
- test/fixtures/CA-NT-2021.json
- test/fixtures/CA-NT-2022.json
- test/fixtures/CA-NT-2023.json
- test/fixtures/CA-NT-2024.json
- test/fixtures/CA-NT-2025.json
- test/fixtures/CA-NT-2026.json
- test/fixtures/CA-NT-2027.json
Modify name based on information found on [this website](https://my.hr.gov.nt.ca/employees/leave-time/statutory-holidays) after confirming the date [here](https://www.rcaanc-cirnac.gc.ca/eng/1100100013718/1534874583157)
> fix: modify holiday name to National Indigenous Peoples Day

- data/countries/SE.yaml
Add english translations for more uncommon days
> Update SE.yaml with english translations

- data/countries/SG.yaml
https://www.mom.gov.sg/employment-practices/public-holidays
> Fix Singapore Hari Raya Puasa date for 2024 - Update SG.yaml

- types/index.d.ts
not tested, but it should just work out of the box
> Remove `string` from HolidayType, so that autocomplete works

- package.json
> chore: run yaml before build

- README.md
> docs: fix description on calling holidays2json.cjs in README

- data/countries/GB.yaml
- test/fixtures/GB-SCT-2019.json
- test/fixtures/GB-SCT-2024.json
- test/fixtures/GB-SCT-2025.json
> fix(GB-SCT,#494): add substitute day for st andrew's day

- data/countries/PL.yaml
- data/names.yaml
- test/fixtures/PL-2015.json
- test/fixtures/PL-2016.json
- test/fixtures/PL-2017.json
- test/fixtures/PL-2018.json
- test/fixtures/PL-2019.json
- test/fixtures/PL-2020.json
- test/fixtures/PL-2021.json
- test/fixtures/PL-2022.json
- test/fixtures/PL-2023.json
- test/fixtures/PL-2024.json
- test/fixtures/PL-2025.json
- test/fixtures/PL-2026.json
- test/fixtures/PL-2027.json
- test/fixtures/PL-2028.json
- test/fixtures/PL-2029.json
Fixes #512 
This PR adds the following holidays for Poland:
- national holidays that aren't public holidays
- commonly celebrated religious holidays
- some additional commonly celebrated observances
> feat(PL, #512): add non-public holidays

- data/countries/VA.yaml
- data/names.yaml
- package.json
- test/fixtures/VA-2015.json
- test/fixtures/VA-2016.json
- test/fixtures/VA-2017.json
- test/fixtures/VA-2018.json
- test/fixtures/VA-2019.json
- test/fixtures/VA-2020.json
- test/fixtures/VA-2021.json
- test/fixtures/VA-2022.json
- test/fixtures/VA-2023.json
- test/fixtures/VA-2024.json
- test/fixtures/VA-2025.json
- test/fixtures/VA-2026.json
- test/fixtures/VA-2027.json
- test/fixtures/VA-2028.json
- test/fixtures/VA-2029.json
Adding fixtures and some name fixes to #552.
> Improved Vatican holidays (fixes)

- data/countries/ID.yaml
- test/fixtures/ID-2025.json
> fix(ID): move Maulid Nabi Muhammad date
