data/holidays.json
data/holidays.yaml

This PR fixes the holiday type for new year's eve. The incorrect value was causing it not to be listed as a holiday.
Two quick questions:
1. Is there a true difference between the optional and observance types?
2. When making a change to `holidays.yaml`, there appeared to be no effect.  However, the change to `holidays.json` did. Is the YAML version unused?
Thanks!

fix wrong type for NYE

---

data/holidays.json
data/holidays.yaml

This PR adds Christmas eve as an optional holiday for the US.

adds christmas eve to list of US holidays

---

data/countries/TR.yaml
data/holidays.json
data/names.yaml
test/fixtures/TR-2015.json
test/fixtures/TR-2016.json
test/fixtures/TR-2017.json
test/fixtures/TR-2018.json
test/fixtures/TR-2019.json
test/fixtures/TR-2020.json

A new holiday is added for Turkey after 15.07.2016. You can check at https://en.wikipedia.org/wiki/Public_holidays_in_Turkey .
Also Turkish name of an islamic holiday name was wrong. It is fixed.
Lastly, test fixtures are updated.

A new holiday for Turkey

---

data/countries/NO.yaml
data/holidays.json
data/names.yaml
test/fixtures/NO-2015.json
test/fixtures/NO-2016.json
test/fixtures/NO-2017.json
test/fixtures/NO-2018.json
test/fixtures/NO-2019.json
test/fixtures/NO-2020.json
test/fixtures/SJ-2015.json
test/fixtures/SJ-2016.json
test/fixtures/SJ-2017.json
test/fixtures/SJ-2018.json
test/fixtures/SJ-2019.json
test/fixtures/SJ-2020.json

Notes:
"Første mai" -> "Arbeidernes dag". This is this day is generally known as; and it's also the translation provided by Google. 
`Frigjøringsdag 1945` -> `Frigjøringsdagen`. We don't actually call it with '1945'.
I've decoupled `Constitution Day` from the internal use of it and said that the Norwegian translation of it is `17. mai`, because that is what we call ours, and not everybody else's.
For example, an other country's `Constitution Day` should still be `Grunnlovsdagen` which is provided in the `data/names.yaml`-file.
I've added `Fathers Day`.
I've added 2nd, 3rd and 4th Sunday of Advent to align consistency. None of these are actually holidays, other than normally noted in calendars, but carry some christian values with them.
Let me know if there's anything that should be …

Fixes and more consistency for Norwegian holidays

---

.travis.yml
package-lock.json
package.json
types/index.d.ts
types/tsconfig.json
types/tslint.json
types/typings.test.ts

Leaves rom how you want to handle `test:ts`.
I'm guessing it is ran automatically since it's prefixed with `test`.
Feedback is appreciated. An ts example could be useful, although the test shows how you would go about it.
Edit: 
`npm test` does not run `npm test:ts` and then there's node 4 support.
Looks like Node 4 has reached EOL.
https://github.com/nodejs/Release#release-schedule

Adding definition file for typescript support

---

LICENSE
data/countries/VA.yaml

I also regenerated the LICENSE by running scripts/attributions.js .
I somewhat randomly came across this and wanted to fix it.

Fixing an attribution typo for Vatican City.

---

README.md
data/countries/DE.yaml
data/holidays.json

See https://de.wikipedia.org/wiki/Baden-W%C3%BCrttemberg

misspelling corrected "Baden Würtemberg" -> "Baden-Württemberg"

---

data/countries/GU.yaml
test/fixtures/GU-2015.json
test/fixtures/GU-2016.json
test/fixtures/GU-2017.json
test/fixtures/GU-2018.json
test/fixtures/GU-2019.json
test/fixtures/GU-2020.json

While fixing #80 it was noticed that Presidents' Day is not observed in Guam hence based on the data-set found all have been corrected.

Fix Guam holidays

---

examples/browser/test.js

dates like this '2019-01-01 00:00:00 -06:00' don't show weekdays in the example.

fix(example): weekdays not shown for some dates

---

types/index.d.ts

Argument `year` of `getHolidays` can be a number as well as string or Date.
Interface `Holiday` has an optional parameter named `substitute`, which is a boolean.

Fix Typescript types

---

types/index.d.ts
types/typings.test.ts

Related to [this comment](https://github.com/commenthol/date-holidays/issues/44#issuecomment-548330984) where I mentioned that form my project I wrote a different typings implementation. This is that typings implementation.
Note that this expects the import to be `import * as Holiday from 'date-holidays'` and requires the tests to be changed as well.

Typings that match module export implementation

---

data/countries/AU.yaml
test/fixtures/AU-SA-2015.json
test/fixtures/AU-SA-2016.json
test/fixtures/AU-SA-2017.json
test/fixtures/AU-SA-2018.json
test/fixtures/AU-SA-2019.json
test/fixtures/AU-SA-2020.json

fixes issue with wrong holiday name using Christmas Eve instead of New Year's Eve for AU.SA

fix(AU-SA): New Year's Eve

---

data/countries/AR.yaml

Argentina has duplicate Shrove Tuesdays (easter -47). This is due to the fact that there is a typo in AR.yaml where Shrove Monday (easter -48) has been incorrectly mapped to Shrove Tuesday (easter -47). This commit fixes the typo by mapping Shrove Monday correctly to easter -48.

Fixed a typo in Argentina file

---

data/countries/DE.yaml

Changed German holiday "Faschingsdienstag" to type `observance`, based on https://en.wikipedia.org/wiki/Public_holidays_in_Germany.
Solves commenthol/date-holidays#144

Changed "Faschingsdienstag" to observance commenthol/date-holidays#144

---

data/countries/SE.yaml
test/fixtures/SE-2015.json
test/fixtures/SE-2016.json
test/fixtures/SE-2017.json
test/fixtures/SE-2018.json
test/fixtures/SE-2019.json
test/fixtures/SE-2020.json
test/fixtures/SE-2021.json
test/fixtures/SE-2022.json
test/fixtures/SE-2023.json
test/fixtures/SE-2024.json
test/fixtures/SE-2025.json

* Added Swedish public holiday _Midsommarafton_ (Midsummer's eve) to `SE.yaml`
* Refactored Swedish public holiday _Midsommar_ :arrow_right: _Midsommardagen_
* Updated test files to reflect new changes
In Sweden, simply _Midsummer_ is not a holiday per se, but consists of two days (see [Wikipedia](https://en.wikipedia.org/wiki/Midsummer#Sweden)), Midsummer's eve and Midsummer's day. Both of these are holidays.
Thanks for a great library!

Added 'midsommarafton' public holiday, old 'midsommar' -> 'midsommardagen'

---

data/countries/HR.yaml

In 2020 there has been a change in Holidays in Croatia, more info at: https://en.wikipedia.org/wiki/Public_holidays_in_Croatia - Updated data to reflect that change
Additionally added the types of the holidays along with the widely observed International Women's day .
Marked the regional holidays as optional because they don't cover the entire county (just the municipal areas of Split and Dubrovnik respectively) and do not necessarily include all types of business and services as public holidays do.

Update HR with 2020 change and add types

---

package.json

When running `npm run watch` I got an error because the package `watch-run` was not installed. I added it as a `devDependency`.
Simple fix. Please review.

fix: Add dependency for watch-run

---

data/countries/JP.yaml
test/fixtures/JP-2016.json
test/fixtures/JP-2017.json
test/fixtures/JP-2018.json
test/fixtures/JP-2019.json
test/fixtures/JP-2020.json
test/fixtures/JP-2021.json
test/fixtures/JP-2022.json
test/fixtures/JP-2023.json
test/fixtures/JP-2024.json
test/fixtures/JP-2025.json

Fixed JP-2021 holidays announced by Tokyo 2020 Olympic and Paralympic Games, Cabinet Secretariat on December 21, 2020.
https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html
* 2021-07-19 Marine Day (海の日) to **2021-07-22**
* 2021-08-11 Mountain Day (山の日) to **2021-08-08** and substitutes holiday **2021-08-09**
* 2021-10-11 Sports Day (スポーツの日) to **2021-07-23**

fix: JP holidays for 2021

---

data/countries/CZ.yaml
test/fixtures/CZ-2015.json
test/fixtures/CZ-2016.json
test/fixtures/CZ-2017.json
test/fixtures/CZ-2018.json
test/fixtures/CZ-2019.json
test/fixtures/CZ-2020.json
test/fixtures/CZ-2021.json
test/fixtures/CZ-2022.json
test/fixtures/CZ-2023.json
test/fixtures/CZ-2024.json
test/fixtures/CZ-2025.json

Change Czech Easter Sunday type to "observance", because it is not listed as a public holiday on [wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic).

Update Czech Easter Sunday

---

docs/specification.md

This adds some additional information to help contributors cite sources. I initially started to put this is CONTRIBUTING.md. However, I think it fits a bit better in the specification which is linked from CONTRIBUTING.md. With that said, I am open to feedback regarding where this should be placed.

Guidelines for citations

---

data/countries/US.yaml
test/fixtures/US-GA-2015.json
test/fixtures/US-GA-2016.json
test/fixtures/US-GA-2017.json
test/fixtures/US-GA-2018.json
test/fixtures/US-GA-2019.json
test/fixtures/US-GA-2020.json
test/fixtures/US-GA-2021.json
test/fixtures/US-GA-2022.json
test/fixtures/US-GA-2023.json
test/fixtures/US-GA-2024.json
test/fixtures/US-GA-2025.json

Georgia fixes building off of the work of @svict4 in #143.
* Updates the names of Confederate holidays to the new generic names to reflect the 2015 change.
* Corrects when Robert E. Lee's birthday is observed.
Here is a song to dedicate this change: https://open.spotify.com/track/0yoQrdGXBlL5syZ2xzgzMU?si=VlQQDPIdQG24hRWLoQe2cA ("Georgia On My Mind" performed by Hoagy Carmichael).

Georgia (US State) updates

---

data/countries/JP.yaml

Thank you for your great work.
I found the result from your package lacks some public holidays according to the Japanese Cabinet Office: 4 of them are due to the imperial ceremonies and 1 is due to the lack of substitution rule.
I fixed them and checked and now the result coincides the data from Japanese Cabinet Office.

Fix(JP): add public holidays and a substitution rule.

---

data/countries/EE.yaml
test/fixtures/EE-2015.json
test/fixtures/EE-2016.json
test/fixtures/EE-2017.json
test/fixtures/EE-2018.json
test/fixtures/EE-2019.json
test/fixtures/EE-2020.json
test/fixtures/EE-2021.json
test/fixtures/EE-2022.json
test/fixtures/EE-2023.json
test/fixtures/EE-2024.json
test/fixtures/EE-2025.json

Estonia (EE) Indepencence day on the 24th of February is marked as observance but it is a national holiday according to https://en.wikipedia.org/wiki/Independence_Day_(Estonia)

Update EE Independence Day to be a public holiday

---

README.md
package.json
types/index.d.ts
webpack.config.cjs

fixes #244 
corrects date-holidays-parser imports and type exports
in your typescript project use
```ts
import Holidays, { HolidaysTypes } from "date-holidays";
```

Fix import and types

---

data/countries/CH.yaml
test/fixtures/CH-GL-2015.json
test/fixtures/CH-GL-2016.json
test/fixtures/CH-GL-2017.json
test/fixtures/CH-GL-2018.json
test/fixtures/CH-GL-2019.json
test/fixtures/CH-GL-2020.json
test/fixtures/CH-GL-2021.json
test/fixtures/CH-GL-2022.json
test/fixtures/CH-GL-2023.json
test/fixtures/CH-GL-2024.json
test/fixtures/CH-GL-2025.json

Näfelser Fahrt does not take place on April 1st. according to
https://www.gl.ch/verwaltung/staatskanzlei/oeffentliche-feiertage.html
Christmas Eve and Syvester added
Eidg. Dank-, Buss- und Bettag not celebrated

fix(CH-GL): Näfelser Fahrt and other holidays

---

data/countries/GB.yaml
test/fixtures/GB-2022.json
test/fixtures/GB-ALD-2022.json
test/fixtures/GB-ENG-2022.json
test/fixtures/GB-NIR-2022.json
test/fixtures/GB-SCT-2022.json
test/fixtures/GB-WLS-2022.json
test/fixtures/GG-2022.json
test/fixtures/GI-2022.json
test/fixtures/IM-2022.json
test/fixtures/JE-2022.json

https://www.gov.uk/government/news/extra-bank-holiday-to-mark-the-queens-platinum-jubilee-in-2022

fix(GB,GG,GI,IM,JE): Queen’s Platinum Jubilee

---

data/countries/GB.yaml
test/fixtures/GB-2022.json
test/fixtures/GB-ALD-2022.json
test/fixtures/GB-ENG-2022.json
test/fixtures/GB-NIR-2022.json
test/fixtures/GB-SCT-2022.json
test/fixtures/GB-WLS-2022.json
test/fixtures/GG-2022.json
test/fixtures/GI-2022.json
test/fixtures/IM-2022.json
test/fixtures/JE-2022.json

The Early May bank holiday was erroneously choosen as being shifted
because of the Queens Platinum Jubilee instead of the Spring bank
holiday.

fix(GB,GG,GI,IM,JE): Replace Early May with Spring bank holiday

---

data/countries/LU.yaml

I don't know where this was taken from, but it's definitely not a public holiday

Remove incorrect public holiday

---

data/countries/ID.yaml
test/fixtures/ID-2015.json
test/fixtures/ID-2016.json
test/fixtures/ID-2017.json
test/fixtures/ID-2018.json
test/fixtures/ID-2019.json
test/fixtures/ID-2020.json
test/fixtures/ID-2021.json
test/fixtures/ID-2022.json
test/fixtures/ID-2023.json
test/fixtures/ID-2024.json
test/fixtures/ID-2025.json

Independence day corrections for Indonesia
Should be 17th August

fix(ID): fixing Indonesia's independence day

---

package.json

The `eslint-plugin-yml` should be in the `devDependencies`, not in the `dependencies`.

Move eslint-plugin-yml to devDependencies

---

data/countries/BE.yaml

The PR corrects a holiday, Easter is considered 'observance' since it's not a paid holiday.

Easter isn't a paid holiday in Belgium

---

data/countries/BE.yaml
test/fixtures/BE-2015.json
test/fixtures/BE-2016.json
test/fixtures/BE-2017.json
test/fixtures/BE-2018.json
test/fixtures/BE-2019.json
test/fixtures/BE-2020.json
test/fixtures/BE-2021.json
test/fixtures/BE-2022.json
test/fixtures/BE-2023.json
test/fixtures/BE-2024.json
test/fixtures/BE-2025.json

Pentecost and the various regional community holidays aren't public holidays.

Mark Pentecost and Regional days as observance

---

data/countries/US.yaml
test/fixtures/US-CA-2015.json
test/fixtures/US-CA-2016.json
test/fixtures/US-CA-2017.json
test/fixtures/US-CA-2018.json
test/fixtures/US-CA-2019.json
test/fixtures/US-CA-2020.json
test/fixtures/US-CA-2021.json
test/fixtures/US-CA-2022.json
test/fixtures/US-CA-2023.json
test/fixtures/US-CA-2024.json
test/fixtures/US-CA-2025.json
test/fixtures/US-CA-LA-2015.json
test/fixtures/US-CA-LA-2016.json
test/fixtures/US-CA-LA-2017.json
test/fixtures/US-CA-LA-2018.json
test/fixtures/US-CA-LA-2019.json
test/fixtures/US-CA-LA-2020.json
test/fixtures/US-CA-LA-2021.json
test/fixtures/US-CA-LA-2022.json
test/fixtures/US-CA-LA-2023.json
test/fixtures/US-CA-LA-2024.json
test/fixtures/US-CA-LA-2025.json

Modified the name to "Presidents' Day" from "The third Monday in February". Used the source https://www.calhr.ca.gov/employees/pages/state-holidays.aspx to confirm the name.

fix(US.CA): Presidents' Day name

---

data/countries/NZ.yaml

The primary source for Matariki dates is 
https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf
linked from
https://www.mbie.govt.nz/business-and-employment/employment-and-skills/employment-legislation-reviews/matariki/matariki-public-holiday/#:~:text=The%20first%20public%20holiday%20to,the%20last%20rising%20of%20Matariki
The Matariki Advisory Committee dates list 21st July 2036 as the holiday, but that's a Monday and all Matariki was defined as always falling on a Friday (in that same doc). This is clearly a misprint. All downstream sources, both news media and govt. press release correct this.
The holiday actually lands on 2036-07-18
https://www.beehive.govt.nz/release/matariki-holiday-dates-next-thirty-years-announced

Fix NZ Matariki 2036 misprint

---

package.json

I was receiving the following after upgrading to TS 4.7 and setting `"moduleResolution": "Node16"` in `tsconfig.json`:
> error TS7016: Could not find a declaration file for module 'date-holidays'. '/.../node_modules/date-holidays/lib/index.cjs' implicitly has an 'any' type.
> Try `npm i --save-dev @types/date-holidays` if it exists or add a new declaration (.d.ts) file containing `declare module 'date-holidays';`
Adding `types` to the `exports` field seems to fix this.

Add types to exports

---

data/countries/IE.yaml

https://github.com/commenthol/date-holidays/issues/362
This is to address that issue, with the proposed fix on October bank holiday which actually Falls on Halloween.

Update Ireland to show the correct October holiday

---

LICENSE
data/countries/LU.yaml
data/names.yaml
test/fixtures/LU-2015.json
test/fixtures/LU-2016.json
test/fixtures/LU-2017.json
test/fixtures/LU-2018.json
test/fixtures/LU-2019.json
test/fixtures/LU-2020.json
test/fixtures/LU-2021.json
test/fixtures/LU-2022.json
test/fixtures/LU-2023.json
test/fixtures/LU-2024.json
test/fixtures/LU-2025.json

- added translations in Luxembourgish (lb)
- added active dates
- renamed 06-23 into National Holiday ("L'anniversaire du Grand-Duc" = the Grand Duke's birthday, it is not the official name, which is "Jour de la célébration de l'anniversaire du Grand-Duc" and the Grand Duke's birthday is currently the 16 April)

Improved support for public holidays in Luxembourg

---

data/countries/LU.yaml

One source was missing from the specification file for the holidays in Luxembourg: the law of 25 april 2019.
https://legilux.public.lu/eli/etat/leg/loi/2019/04/25/a271/jo
This PR adds it.

missing source for Luxembourg

---

data/countries/IE.yaml
test/fixtures/IE-2015.json
test/fixtures/IE-2016.json
test/fixtures/IE-2017.json
test/fixtures/IE-2018.json
test/fixtures/IE-2019.json
test/fixtures/IE-2020.json
test/fixtures/IE-2021.json
test/fixtures/IE-2022.json
test/fixtures/IE-2023.json
test/fixtures/IE-2024.json
test/fixtures/IE-2025.json

In December, even if its a week day, its a bank holiday, so the and is the correct version of the 27th.

2nd of january and 27th of dec is a bank holiday

---

LICENSE
data/countries/NO.yaml
data/names.yaml
test/fixtures/NO-2015.json
test/fixtures/NO-2016.json
test/fixtures/NO-2017.json
test/fixtures/NO-2018.json
test/fixtures/NO-2019.json
test/fixtures/NO-2020.json
test/fixtures/NO-2021.json
test/fixtures/NO-2022.json
test/fixtures/NO-2023.json
test/fixtures/NO-2024.json
test/fixtures/NO-2025.json
test/fixtures/SJ-2015.json
test/fixtures/SJ-2016.json
test/fixtures/SJ-2017.json
test/fixtures/SJ-2018.json
test/fixtures/SJ-2019.json
test/fixtures/SJ-2020.json
test/fixtures/SJ-2021.json
test/fixtures/SJ-2022.json
test/fixtures/SJ-2023.json
test/fixtures/SJ-2024.json
test/fixtures/SJ-2025.json

Added flag days and other missing holidays and international days.
New additions are:
- All official flag days
- Valentines, International Women's Day, and April Fools
- Other minor holidays like Allehelgensaften, and Askeonsdag
Corrections:
Name of 17. may changed from "17. mai" to "Grunnlovsdagen", to name it like it is named as a flag day.

Add flag days and missing holidays norway

---

data/countries/US.yaml
test/fixtures/US-MD-2015.json
test/fixtures/US-MD-2016.json
test/fixtures/US-MD-2017.json
test/fixtures/US-MD-2018.json
test/fixtures/US-MD-2019.json
test/fixtures/US-MD-2020.json
test/fixtures/US-MD-2021.json
test/fixtures/US-MD-2022.json
test/fixtures/US-MD-2023.json
test/fixtures/US-MD-2024.json
test/fixtures/US-MD-2025.json
test/fixtures/US-MD-2026.json
test/fixtures/US-MD-2027.json

This is no longer a holiday in Maryland, as seen on this list of state holidays: https://dbm.maryland.gov/employees/Pages/StateHolidays2023.aspx

feat: remove service reduction day in US.MD

---

data/countries/TH.yaml

This PR fixes the incorrect holidays translation for Thailand's Songkran Day, which has previously been labelled as `"Chakri Memorial Day"`.

[TH] Fixing wrong translation for Songkran Day

---

data/countries/BE.yaml
test/fixtures/BE-VLG-2015.json
test/fixtures/BE-VLG-2016.json
test/fixtures/BE-VLG-2017.json
test/fixtures/BE-VLG-2018.json
test/fixtures/BE-VLG-2019.json
test/fixtures/BE-VLG-2020.json
test/fixtures/BE-VLG-2021.json
test/fixtures/BE-VLG-2022.json
test/fixtures/BE-VLG-2023.json
test/fixtures/BE-VLG-2024.json
test/fixtures/BE-VLG-2025.json
test/fixtures/BE-VLG-2026.json
test/fixtures/BE-VLG-2027.json

with note on 11-02, 11-15, 12-26 that employees of the Flemish government celebrate a day-off
Fixes #424

fix(BE-VLG,#424): add boxing day as observance

---

data/countries/AT.yaml

Hi, thanks so much for this library, amazing!
A quick update to Leopoldi-Tag in Austria - this is a partial (optional) holiday, only for Schüler (students) and, in Niederösterreich, Beamten (government workers)

Make Leopoldi-Tag optional , add notes and source

---

TODO.md
data/countries/UA.yaml
data/names.yaml
test/fixtures/UA-2015.json
test/fixtures/UA-2016.json
test/fixtures/UA-2017.json
test/fixtures/UA-2018.json
test/fixtures/UA-2019.json
test/fixtures/UA-2020.json
test/fixtures/UA-2021.json
test/fixtures/UA-2022.json
test/fixtures/UA-2023.json
test/fixtures/UA-2024.json
test/fixtures/UA-2025.json
test/fixtures/UA-2026.json
test/fixtures/UA-2027.json

See https://www.kyivpost.com/post/18846
- Christmas be celebrated on December 25 instead of January 7.
- July 15 as the new date for the celebration of the Day of Ukrainian Statehood, replacing the previous date of the 28th
- Day of Defenders moved from October 14 to October 1.
- Corrected 05-02 as not being celebrated since 2018

feat(UA): Update ukrainian holidays

---

data/countries/US.yaml
test/fixtures/US-IA-2018.json
test/fixtures/US-IA-2019.json
test/fixtures/US-IA-2020.json
test/fixtures/US-IA-2021.json
test/fixtures/US-IA-2022.json
test/fixtures/US-IA-2023.json
test/fixtures/US-IA-2024.json
test/fixtures/US-IA-2025.json
test/fixtures/US-IA-2026.json
test/fixtures/US-IA-2027.json

Since 2018, Iowa (US.IA) has recognized the second Monday in October as `Indigenous Peoples Day`, not 'Columbus Day`. This PR updates US.yaml to reflect this and adds an explanatory source.

Modify holiday name for iowa

---

data/countries/NL.yaml
test/fixtures/NL-2015.json
test/fixtures/NL-2016.json
test/fixtures/NL-2017.json
test/fixtures/NL-2018.json
test/fixtures/NL-2019.json
test/fixtures/NL-2020.json
test/fixtures/NL-2021.json
test/fixtures/NL-2022.json
test/fixtures/NL-2023.json
test/fixtures/NL-2024.json
test/fixtures/NL-2025.json
test/fixtures/NL-2026.json
test/fixtures/NL-2027.json

* Changed type of Goede Vrijdag (Good Friday) from public to school
* Changed type of Bevrijdingsdag (Liberation Day) from observance to school
* Set name of Ascension Day to Hemelvaartsdag as an override
* Belgium has O.L.H. Hemelvaart and O.L.V. Hemelvaart, but in the Netherlands we only have the former and it's called Hemelvaartsdag in official sources.
* The official Belgian names are unclear as Hemelvaartsdag and Maria-Hemelvaart are also used in official sources (compare https://www.belgium.be/nl/over_belgie/land/belgie_in_een_notendop/feestdagen and https://www.belgium.be/nl/werk/verlof_en_loopbaanonderbrekingen/feestdagen). I decided not to mess with the overall Dutch translation for Ascension Day.
* Add historical definitions for Koninginnedag (Queen's Day) and Princessedag …

Improve holiday definitions for The Netherlands

---

data/countries/ZA.yaml

This pull request adds an entry to the `ZA.yaml` file, introducing a new public holiday on December 15, 2023. This date has been declared as a public holiday by President Cyril Ramaphosa to celebrate the Springboks' victory in the 2023 Rugby World Cup.
- Inserted a new date for the once-off public holiday on 15 December 2023 as "Rugby World Cup Win Public Holiday."
This update reflects the official declaration made by the South African government, as published in the Government Gazette, and further communicated through a news bulletin by SAnews, the official South African Government News Agency. The announcement is a mark of national celebration, honoring the Springboks' triumph at the Rugby World Cup and the unifying effect it has had on the nation.
For further reference, you can find …

Add Special Public Holiday for South Africa on 15 Dec 2023 in Celebration of Rugby World Cup Victory

---

package.json
scripts/holidays2json.cjs

Use of lodash instead of lodash.pick, lodash.omit since the modularised versions haven't been updated in many years.

fix(#452): replace lodash.pick with lodash

---

data/countries/HU.yaml
test/fixtures/HU-2015.json
test/fixtures/HU-2016.json
test/fixtures/HU-2017.json
test/fixtures/HU-2018.json
test/fixtures/HU-2019.json
test/fixtures/HU-2020.json
test/fixtures/HU-2021.json
test/fixtures/HU-2022.json
test/fixtures/HU-2023.json
test/fixtures/HU-2024.json
test/fixtures/HU-2025.json
test/fixtures/HU-2026.json
test/fixtures/HU-2027.json

Hello,
this PR should resolve this issue https://github.com/commenthol/date-holidays/issues/464.
Info sources:
- https://studyinhungary.hu/living-in-hungary/menu/national-holidays.html
- https://en.wikipedia.org/wiki/Public_holidays_in_Hungary
- https://publicholidays.hu/revolution-day/

fix(HU,#464): update the name of the public holiday on March 15

---

CHANGELOG.md
LICENSE
data/countries/NL.yaml
data/names.yaml
test/fixtures/NL-2015.json
test/fixtures/NL-2016.json
test/fixtures/NL-2017.json
test/fixtures/NL-2018.json
test/fixtures/NL-2019.json
test/fixtures/NL-2020.json
test/fixtures/NL-2021.json
test/fixtures/NL-2022.json
test/fixtures/NL-2023.json
test/fixtures/NL-2024.json
test/fixtures/NL-2025.json
test/fixtures/NL-2026.json
test/fixtures/NL-2027.json

For almost fifteen years, I have been maintaining https://github.com/PanderMusubi/dutch-holidays (which was also used by Thunderbird) and would like to contribute to this project and slowly move the relevant data to here.

improved Dutch translations

---

data/countries/AU.yaml
test/fixtures/AU-WA-2024.json

In Western Australia the King's Birthday is `2024-09-23` instead of the expected date of `2024-09-30`.
Just for this year it seems. There's no particular reason or rule that could be amended going forward.
Source: https://www.commerce.wa.gov.au/labour-relations/public-holidays-western-australia

fix: correct Kings Birthday in Western Australia for 2024

---

data/countries/IT.yaml
test/fixtures/IT-52-2015.json
test/fixtures/IT-52-2016.json
test/fixtures/IT-52-2017.json
test/fixtures/IT-52-2018.json
test/fixtures/IT-52-2019.json
test/fixtures/IT-52-2020.json
test/fixtures/IT-52-2021.json
test/fixtures/IT-52-2022.json
test/fixtures/IT-52-2023.json
test/fixtures/IT-52-2024.json
test/fixtures/IT-52-2025.json
test/fixtures/IT-52-2026.json
test/fixtures/IT-52-2027.json
test/fixtures/IT-52-FI-2015.json
test/fixtures/IT-52-FI-2016.json
test/fixtures/IT-52-FI-2017.json
test/fixtures/IT-52-FI-2018.json
test/fixtures/IT-52-FI-2019.json
test/fixtures/IT-52-FI-2020.json
test/fixtures/IT-52-FI-2021.json
test/fixtures/IT-52-FI-2022.json
test/fixtures/IT-52-FI-2023.json
test/fixtures/IT-52-FI-2024.json
test/fixtures/IT-52-FI-2025.json
test/fixtures/IT-52-FI-2026.json
test/fixtures/IT-52-FI-2027.json

- Add June 24th (San Giovanni Battista) as the patron saint holiday for Florence, Italy
- Source: https://it.wikipedia.org/wiki/Firenze

feat(IT): add Florence patron saint holiday

---

data/countries/IE.yaml
test/fixtures/IE-2015.json
test/fixtures/IE-2016.json
test/fixtures/IE-2017.json
test/fixtures/IE-2018.json
test/fixtures/IE-2019.json
test/fixtures/IE-2020.json
test/fixtures/IE-2021.json
test/fixtures/IE-2022.json
test/fixtures/IE-2023.json
test/fixtures/IE-2024.json
test/fixtures/IE-2025.json
test/fixtures/IE-2026.json
test/fixtures/IE-2027.json

According to https://www.bankholidays.ie/bank-holiday-dates-ireland-2024 there is no bank holiday on December 27th.
Fixes issue #495

fix(IE,#495): removal of Christmas bank holiday

---

data/countries/RO.yaml
test/fixtures/RO-2015.json
test/fixtures/RO-2016.json
test/fixtures/RO-2017.json
test/fixtures/RO-2018.json
test/fixtures/RO-2019.json
test/fixtures/RO-2020.json
test/fixtures/RO-2021.json
test/fixtures/RO-2022.json
test/fixtures/RO-2023.json
test/fixtures/RO-2024.json
test/fixtures/RO-2025.json
test/fixtures/RO-2026.json
test/fixtures/RO-2027.json

Update public holidays for RO country.
Source: https://en.wikipedia.org/wiki/Public_holidays_in_Romania

Update RO data 

---

data/countries/IE.yaml
test/fixtures/IE-2015.json
test/fixtures/IE-2016.json
test/fixtures/IE-2017.json
test/fixtures/IE-2018.json
test/fixtures/IE-2019.json
test/fixtures/IE-2020.json
test/fixtures/IE-2021.json
test/fixtures/IE-2022.json
test/fixtures/IE-2023.json
test/fixtures/IE-2024.json
test/fixtures/IE-2025.json
test/fixtures/IE-2026.json
test/fixtures/IE-2027.json

The first Monday in January is not a bank holiday in Ireland.
I checked this website all the way back to 2015 and it has not been one in at least that long: https://www.timeanddate.com/holidays/ireland/2025

feat: remove bank holiday and update test fixtures

---

data/countries/MX.yaml
test/fixtures/MX-2015.json
test/fixtures/MX-2016.json
test/fixtures/MX-2017.json
test/fixtures/MX-2018.json
test/fixtures/MX-2019.json
test/fixtures/MX-2020.json
test/fixtures/MX-2021.json
test/fixtures/MX-2022.json
test/fixtures/MX-2023.json
test/fixtures/MX-2024.json
test/fixtures/MX-2025.json
test/fixtures/MX-2026.json
test/fixtures/MX-2027.json
test/fixtures/MX-2028.json
test/fixtures/MX-2029.json

This pull request addresses inaccuracies in the definitions for three Mexican holidays: Constitution Day, Benito Juárez's Birthday, and Revolution Day. The original historical dates and the shifted observed dates (the Monday off) were both defined without year restrictions, leading to the potential for the same holiday to be counted *twice* in a single year.
This PR updates the definitions to accurately reflect when each date was valid, ensuring the library provides correct results for both historical and modern holiday calculations. Each definition now includes year information to specify its validity period.
According to the government document "[Ley Federal del Trabajo](https://www.gob.mx/cms/uploads/attachment/file/156203/1044_Ley_Federal_del_Trabajo.pdf)", the legal change shifting …

fix(MX): correct Mexican holiday definitions, prevent duplicate occurrences.

---

.github/workflows/ci.yml

This PR introduces manual triggering for the CI workflow via a "Run workflow" button (using the `workflow_dispatch` event) on the Actions > CI page.
**Benefits:**
*   **For Contributors:** Allows running the CI pipeline on their forked repositories *before* submitting a pull request, enabling them to catch and fix errors early.
*   **For Maintainers:** Reduces the number of pull requests with failing CI, saving time and effort.

ci: add workflow_dispatch trigger to run CI on any commit

---

data/countries/AR.yaml
test/fixtures/AR-2015.json
test/fixtures/AR-2016.json
test/fixtures/AR-2017.json
test/fixtures/AR-2018.json
test/fixtures/AR-2019.json
test/fixtures/AR-2020.json
test/fixtures/AR-2021.json
test/fixtures/AR-2022.json
test/fixtures/AR-2023.json
test/fixtures/AR-2024.json
test/fixtures/AR-2025.json
test/fixtures/AR-2026.json
test/fixtures/AR-2027.json
test/fixtures/AR-2028.json
test/fixtures/AR-2029.json

This pull request provides a comprehensive update to the holiday data for Argentina (AR), covering the period from 1976 to 2025.
- **Improved Comprehensiveness and Accuracy**:
- Added and updated holiday information for the years 1976 to 2025.
- Thoroughly tracked the history of holiday name changes (e.g., "Day of Respect for Cultural Diversity") and changes in the rules governing movable holidays.
- Incorporated numerous sources of information, including laws, decrees, presidential decrees, and resolutions, to ensure the accuracy, reliability, and traceability of each holiday.
- Corrected existing holiday names to reflect more common and accurate terminology.
- **Support for Single-Year Holidays and One-Off Date Modifications**:
- Accurately represented holidays that are valid for a …

feat(AR): Update Argentine holiday data comprehensively (1976-2025)

---

README.md
data/countries/LI.yaml

Correct spelling of the country of Liechtenstein. Changed Lichtenstein -> Liechtenstein

correct spelling of Liechtenstein

---

data/countries/DE.yaml
test/fixtures/DE-HE-2015.json
test/fixtures/DE-HE-2016.json
test/fixtures/DE-HE-2017.json
test/fixtures/DE-HE-2018.json
test/fixtures/DE-HE-2019.json
test/fixtures/DE-HE-2020.json
test/fixtures/DE-HE-2021.json
test/fixtures/DE-HE-2022.json
test/fixtures/DE-HE-2023.json
test/fixtures/DE-HE-2024.json
test/fixtures/DE-HE-2025.json
test/fixtures/DE-HE-2026.json
test/fixtures/DE-HE-2027.json
test/fixtures/DE-HE-2028.json
test/fixtures/DE-HE-2029.json

According to the Law in Hessen, neither the Easter nor the Pentecost Sundays are public holidays in Germany-Hessen. See the reference here:
https://www.rv.hessenrecht.hessen.de/bshe/document/jlr-FeiertGHE1952rahmen
Here also as a quote:
--------------
(1) Gesetzliche Feiertage sind die Sonntage sowie
1.  der Neujahrstag,
2.  der Karfreitag,
3.  der Ostermontag,
4.  der 1. Mai,
5.  der Himmelfahrtstag,
6.  der Pfingstmontag,
7.  der Fronleichnamstag,
8.  der Tag der Deutschen Einheit,
9.  der 1. und 2. Weihnachtstag.
(2) Der zweitletzte Sonntag nach Trinitatis ist Gedenktag für die Opfer des Nationalsozialismus und die Toten beider Weltkriege (Volkstrauertag).
(3) Der letzte Sonntag nach Trinitatis ist Totensonntag. 
-------------

Remove Easter and Pentecost Sundays from DE-HE

---

data/countries/HK.yaml
test/fixtures/HK-2015.json
test/fixtures/HK-2016.json
test/fixtures/HK-2017.json
test/fixtures/HK-2018.json
test/fixtures/HK-2019.json
test/fixtures/HK-2020.json
test/fixtures/HK-2021.json
test/fixtures/HK-2022.json
test/fixtures/HK-2023.json
test/fixtures/HK-2024.json
test/fixtures/HK-2025.json
test/fixtures/HK-2026.json
test/fixtures/HK-2027.json
test/fixtures/HK-2028.json
test/fixtures/HK-2029.json

1. Standardize on Traditional Chinese only (instead of mixing them with some of the Simplified Chinese). Not appending substitute day string also for this reason.
2. Fix holidays fall on Sunday.
3. Format follows official gov website (https://www.gov.hk/en/about/abouthk/holiday), according to data on 2016-2025.

fix(HK): Fix Hong Kong holidays

---

CONTRIBUTING.md
data/countries/CA.yaml
test/fixtures/CA-NT-2015.json
test/fixtures/CA-NT-2016.json
test/fixtures/CA-NT-2017.json
test/fixtures/CA-NT-2018.json
test/fixtures/CA-NT-2019.json
test/fixtures/CA-NT-2020.json
test/fixtures/CA-NT-2021.json
test/fixtures/CA-NT-2022.json
test/fixtures/CA-NT-2023.json
test/fixtures/CA-NT-2024.json
test/fixtures/CA-NT-2025.json
test/fixtures/CA-NT-2026.json
test/fixtures/CA-NT-2027.json
test/fixtures/CA-NT-2028.json
test/fixtures/CA-NT-2029.json
test/fixtures/CA-YT-2017.json
test/fixtures/CA-YT-2018.json
test/fixtures/CA-YT-2019.json
test/fixtures/CA-YT-2020.json
test/fixtures/CA-YT-2021.json
test/fixtures/CA-YT-2022.json
test/fixtures/CA-YT-2023.json
test/fixtures/CA-YT-2024.json
test/fixtures/CA-YT-2025.json
test/fixtures/CA-YT-2026.json
test/fixtures/CA-YT-2027.json
test/fixtures/CA-YT-2028.json
test/fixtures/CA-YT-2029.json

External sources:
https://en.wikipedia.org/wiki/National_Indigenous_Peoples_Day
https://www.thecanadianencyclopedia.ca/en/article/national-aboriginal-day
Issue:
#549
Changes:
- Add start year 2001 to NT province for NIPD
- Copy that exact same configuration to YT province, since in 2017
- Write test fixtures
- Add a step to CONTRIBUTING.md to run `npm install` before running `npm run build`

Add National Indigenous Peoples Day for Yukon Province Canada
